import {useEffect,useMemo,useState} from "react";
import {supabase} from "./lib/supabase";
import {Activity,ArrowDownToLine,ArrowUpFromLine,BarChart3,Blocks,CheckCircle2,ChevronRight,Coins,FileClock,LayoutDashboard,LogOut,Menu,RefreshCw,Search,ShieldCheck,UserRound,Users,WalletCards,XCircle} from "lucide-react";

type Page="dashboard"|"users"|"deposits"|"withdrawals"|"investments"|"transactions"|"audit";
type Row=Record<string,any>;

const pages:{id:Page;label:string;icon:any}[]=[
{id:"dashboard",label:"Dashboard",icon:LayoutDashboard},{id:"users",label:"Users",icon:Users},
{id:"deposits",label:"Deposits",icon:ArrowDownToLine},{id:"withdrawals",label:"Withdrawals",icon:ArrowUpFromLine},
{id:"investments",label:"Investments",icon:BarChart3},{id:"transactions",label:"Transactions",icon:WalletCards},{id:"audit",label:"Audit",icon:FileClock}
];

function fmt(n:any){return Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});}
function date(v:any){return v?new Date(v).toLocaleString():"—";}

export default function App(){
 const [session,setSession]=useState<any>(null),[checking,setChecking]=useState(true),[allowed,setAllowed]=useState(false);
 const [page,setPage]=useState<Page>("dashboard"),[mobile,setMobile]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[loginBusy,setLoginBusy]=useState(false);
 const [users,setUsers]=useState<Row[]>([]),[txs,setTxs]=useState<Row[]>([]),[investments,setInvestments]=useState<Row[]>([]),[query,setQuery]=useState("");
 const [selected,setSelected]=useState<Row|null>(null),[reason,setReason]=useState("");
 const [amount,setAmount]=useState(""),[block,setBlock]=useState(false);
 const [notice,setNotice]=useState("");

 async function checkUser(s:any){
   if(!s){setAllowed(false);setChecking(false);return;}
   const {data,error}=await supabase.rpc("is_admin");
   if(error||data!==true){await supabase.auth.signOut();setAllowed(false);setError("This account is not authorized for the Global Beldex admin console.");}
   else setAllowed(true);
   setChecking(false);
 }
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);checkUser(data.session);});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);checkUser(s)});return()=>subscription.unsubscribe()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setLoginBusy(true);setError("");const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else{setSession(data.session);await checkUser(data.session)}setLoginBusy(false);}
 async function logout(){await supabase.auth.signOut();setSession(null);setAllowed(false);}
 async function load(){
   setBusy(true);setError("");
   const [u,t,i]=await Promise.all([
     supabase.rpc("admin_search_users",{p_query:"",p_limit:100}),
     supabase.from("transaction").select("id,user_id,type,amount,status,method,note,created_at").order("created_at",{ascending:false}).limit(200),
     supabase.from("user_investment").select("id,user_id,plan_name,principal,daily_rate,duration_days,credited_profit,status,started_at,completed_at").order("started_at",{ascending:false}).limit(100)
   ]);
   if(u.error||t.error||i.error)setError(u.error?.message||t.error?.message||i.error?.message||"Unable to load data.");
   setUsers(u.data||[]);setTxs(t.data||[]);setInvestments(i.data||[]);setBusy(false);
 }
 useEffect(()=>{if(allowed)load()},[allowed]);
 const stats=useMemo(()=>({users:users.length,blocked:users.filter(x=>x.blocked).length,pending:txs.filter(x=>String(x.status).toLowerCase().includes("pending")||String(x.status).toLowerCase().includes("await")).length,active:investments.filter((x:Row)=>x.status==="active").length}),[users,txs,investments]);
 async function rpc(name:string,args:Row){setBusy(true);setError("");setNotice("");const {error}=await supabase.rpc(name,args);if(error)setError(error.message);else{setNotice("Action completed successfully.");await load();setSelected(null);setReason("");setAmount("")}setBusy(false);}
 function chooseUser(u:Row){setSelected(u);setAmount("");setReason("");setBlock(Boolean(u.blocked));}
 async function fund(){if(!selected)return;await rpc("admin_fund_user",{p_user_id:selected.user_id,p_amount:Number(amount),p_reason:reason});}
 async function adjust(){if(!selected)return;await rpc("admin_adjust_balance",{p_user_id:selected.user_id,p_delta:Number(amount),p_reason:reason});}
 async function toggleBlock(){if(!selected)return;await rpc("admin_set_user_block",{p_user_id:selected.user_id,p_blocked:!selected.blocked,p_reason:reason});}
 async function approve(id:string,type:"deposit"|"withdrawal"){await rpc(type==="deposit"?"admin_approve_deposit":"admin_approve_withdrawal",{p_transaction_id:id,p_reason:reason||"Approved from admin console"});}
 async function reject(id:string,type:"deposit"|"withdrawal"){await rpc(type==="deposit"?"admin_reject_deposit":"admin_reject_withdrawal",{p_transaction_id:id,p_reason:reason||"Rejected from admin console"});}
 if(checking)return <div className="center"><div className="loader"/>Checking administrator access…</div>;
 if(!session||!allowed)return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} login={login} busy={loginBusy} error={error}/>;
 const nav=<aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><ShieldCheck/><div><b>GLOBAL BELDEX</b><span>ADMIN CONSOLE</span></div><button className="icon mobileOnly" onClick={()=>setMobile(false)}><XCircle size={18}/></button></div><nav>{pages.map(p=>{const I=p.icon;return <button key={p.id} className={page===p.id?"nav active":"nav"} onClick={()=>{setPage(p.id);setMobile(false)}}><I size={18}/>{p.label}<ChevronRight size={14}/></button>})}</nav><div className="sidebarBottom"><div className="secure"><ShieldCheck size={16}/><span>Database-authorized</span></div><button className="logout" onClick={logout}><LogOut size={16}/>Sign out</button></div></aside>;
 return <div className="app">{nav}<main className="main"><header><button className="icon mobileOnly" onClick={()=>setMobile(true)}><Menu/></button><div><div className="eyebrow">SECURE OPERATIONS</div><h1>{pages.find(x=>x.id===page)?.label}</h1></div><div className="headerActions"><button className="icon" onClick={load} title="Refresh"><RefreshCw size={17}/></button><span className="adminEmail">{session.user.email}</span></div></header>{error&&<div className="alert error"><XCircle size={17}/>{error}</div>}{notice&&<div className="alert success"><CheckCircle2 size={17}/>{notice}</div>}{page==="dashboard"&&<Dashboard stats={stats} txs={txs} users={users}/>} {page==="users"&&<UsersPage users={users} query={query} setQuery={setQuery} chooseUser={chooseUser}/>} {page==="deposits"&&<Queue rows={txs.filter(x=>x.type==="deposit")} kind="deposit" approve={approve} reject={reject} reason={reason} setReason={setReason} busy={busy}/>} {page==="withdrawals"&&<Queue rows={txs.filter(x=>x.type==="withdraw")} kind="withdrawal" approve={approve} reject={reject} reason={reason} setReason={setReason} busy={busy}/>} {page==="investments"&&<Investments rows={investments}/>} {page==="transactions"&&<Transactions rows={txs}/>} {page==="audit"&&<Audit/>}{selected&&<UserModal user={selected} amount={amount} setAmount={setAmount} reason={reason} setReason={setReason} fund={fund} adjust={adjust} toggleBlock={toggleBlock} close={()=>setSelected(null)} busy={busy}/>}</main></div>
}

function Login(p:any){return <div className="login"><div className="loginCard"><div className="logo"><ShieldCheck size={32}/></div><div className="eyebrow">GLOBAL BELDEX</div><h1>Administrator sign in</h1><p>Restricted console. Your Supabase account must be authorized in the admin database.</p><form onSubmit={p.login}><label>Email<input type="email" value={p.email} onChange={e=>p.setEmail(e.target.value)} required autoComplete="username"/></label><label>Password<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)} required autoComplete="current-password"/></label>{p.error&&<div className="formError">{p.error}</div>}<button className="primary" disabled={p.busy}>{p.busy?"Signing in…":"Sign in securely"}</button></form><small>Financial actions are executed by protected PostgreSQL RPCs. No service-role key is shipped to this browser.</small></div></div>}

function Dashboard({stats,txs,users}:any){return <section><div className="grid4"><Card icon={Users} label="Users" value={stats.users}/><Card icon={Blocks} label="Blocked accounts" value={stats.blocked}/><Card icon={Activity} label="Pending transactions" value={stats.pending}/><Card icon={Coins} label="Active investments" value={stats.active}/></div><div className="two"><div className="panel"><div className="panelHead"><h2>Recent transactions</h2><span>Latest 8</span></div><Table headers={["Type","Amount","Status","Created"]} rows={txs.slice(0,8)} cells={(r:Row)=><><td><span className="pill">{r.type}</span></td><td>USD {fmt(r.amount)}</td><td><Status value={r.status}/></td><td>{date(r.created_at)}</td></>}/></div><div className="panel"><div className="panelHead"><h2>Account overview</h2></div><div className="statRows"><div><span>Total visible balance</span><b>USD {fmt(users.reduce((a:number,u:Row)=>a+Number(u.available_balance||0),0))}</b></div><div><span>Locked balance</span><b>USD {fmt(users.reduce((a:number,u:Row)=>a+Number(u.locked_balance||0),0))}</b></div><div><span>BDX balance</span><b>{fmt(users.reduce((a:number,u:Row)=>a+Number(u.bdx_balance||0),0))} BDX</b></div></div></div></div></section>}

function Card({icon:Icon,label,value}:any){return <div className="card"><Icon size={19}/><span>{label}</span><b>{value}</b></div>}
function UsersPage({users,query,setQuery,chooseUser}:any){const list=users.filter((u:Row)=>[u.fullname,u.email,u.user_id].join(" ").toLowerCase().includes(query.toLowerCase()));return <section className="panel"><div className="panelHead"><div><h2>User management</h2><span>Read through RLS; mutations use admin RPCs.</span></div><div className="search"><Search size={16}/><input placeholder="Search name, email or UUID" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><Table headers={["User","Available","Locked","BDX","Status",""]} rows={list} cells={(r:Row)=><><td><b>{r.fullname||"Unnamed"}</b><small>{r.email||r.user_id}</small></td><td>USD {fmt(r.available_balance)}</td><td>USD {fmt(r.locked_balance)}</td><td>{fmt(r.bdx_balance)}</td><td><Status value={r.blocked?"blocked":"active"}/></td><td><button className="linkBtn" onClick={()=>chooseUser(r)}>Manage</button></td></>}/></section>}

function Queue({rows,kind,approve,reject,reason,setReason,busy}:any){const pending=rows.filter((r:Row)=>["pending","awaiting"].includes(String(r.status).toLowerCase()));return <section className="panel"><div className="panelHead"><div><h2>{kind==="deposit"?"Deposit queue":"Withdrawal queue"}</h2><span>{pending.length} pending item(s)</span></div></div><div className="reasonBar"><input placeholder="Reason / approval note" value={reason} onChange={e=>setReason(e.target.value)}/></div><Table headers={["Transaction","User","Amount","Method","Status","Created","Action"]} rows={rows} cells={(r:Row)=><><td>{r.id.slice(0,8)}…</td><td>{r.user_id.slice(0,8)}…</td><td>USD {fmt(r.amount)}</td><td>{r.method||"—"}</td><td><Status value={r.status}/></td><td>{date(r.created_at)}</td><td>{["pending","awaiting"].includes(String(r.status).toLowerCase())?<div className="actions"><button className="approve" disabled={busy} onClick={()=>approve(r.id,kind)}>Approve</button><button className="reject" disabled={busy} onClick={()=>reject(r.id,kind)}>Reject</button></div>:<span className="muted">No action</span>}</td></>}/></section>}

function Investments({rows}:any){return <section className="panel"><div className="panelHead"><div><h2>Investments</h2><span>Portfolio records visible to the authenticated administrator.</span></div></div><Table headers={["Plan","Principal","Daily rate","Profit","Duration","Status","Started"]} rows={rows} cells={(r:Row)=><><td><b>{r.plan_name||"Plan"}</b><small>{r.user_id?.slice(0,8)}…</small></td><td>USD {fmt(r.principal)}</td><td>{fmt(r.daily_rate)}%</td><td>USD {fmt(r.credited_profit)}</td><td>{r.duration_days} days</td><td><Status value={r.status}/></td><td>{date(r.started_at)}</td></>}/></section>}
function Transactions({rows}:any){return <section className="panel"><div className="panelHead"><h2>All transactions</h2><span>{rows.length} loaded</span></div><Table headers={["Type","Amount","Method","Status","User","Created","Note"]} rows={rows} cells={(r:Row)=><><td><span className="pill">{r.type}</span></td><td>USD {fmt(r.amount)}</td><td>{r.method||"—"}</td><td><Status value={r.status}/></td><td>{r.user_id.slice(0,8)}…</td><td>{date(r.created_at)}</td><td>{r.note||"—"}</td></>}/></section>}
function Audit(){return <section className="panel"><div className="empty"><FileClock size={36}/><h2>Audit trail</h2><p>The database audit table is restricted to authenticated administrators. The dedicated viewer will be enabled in the next admin-console update.</p></div></section>}
function UserModal({user,amount,setAmount,reason,setReason,fund,adjust,toggleBlock,close,busy}:any){return <div className="overlay"><div className="modal"><div className="panelHead"><div><h2>Manage user</h2><span>{user.email||user.user_id}</span></div><button className="icon" onClick={close}><XCircle/></button></div><div className="profileGrid"><div><span>Available</span><b>USD {fmt(user.available_balance)}</b></div><div><span>Locked</span><b>USD {fmt(user.locked_balance)}</b></div><div><span>BDX</span><b>{fmt(user.bdx_balance)}</b></div></div><label>Amount / adjustment<input type="number" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for financial/admin actions"/></label><div className="modalActions"><button className="primary" disabled={busy||!amount||!reason} onClick={fund}>Fund user</button><button className="secondary" disabled={busy||!amount||!reason} onClick={adjust}>Adjust +/−</button><button className={user.blocked?"secondary":"danger"} disabled={busy||!reason} onClick={toggleBlock}>{user.blocked?"Unblock account":"Block account"}</button></div><small>All actions are authorized by PostgreSQL permissions and recorded in the admin audit trail.</small></div></div>}
function Status({value}:any){const v=String(value||"unknown");return <span className={"status "+v.toLowerCase()}>{v}</span>}
function Table({headers,rows,cells}:any){return <div className="tableWrap">{rows.length?<table><thead><tr>{headers.map((h:string)=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r:Row,i:number)=><tr key={r.id||i}>{cells(r)}</tr>)}</tbody></table>:<div className="empty"><Search size={28}/><p>No records found.</p></div>}</div>}
